### ISSUE TITLE
Add minimum version of NodeJS required

### ISSUE THREAD

**Issue by hanak** [bloop-box/bloop-server-tester#1]
Minimum required NodeJS version has to support a top-level `await` in order to run the script. However, this support has been added in version 16 or so. Adding a minimum required NodeJS version in the documentation might save a user a few minutes.

**Comment by DASPRiD** [comment]
I don't see a particular need for that. Node 15 reached EOL 2 years ago, Node 14 (LTS) reached it end of April this year. So neither should be used anymore by anyone at this point.

**Comment by DASPRiD** [comment]
With Node16 also already reached EOL a month ago, I'm closing this issue.
